# Generated by Django 4.2.3 on 2023-08-17 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('portions', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shopping list', max_length=128)),
                ('creation_date', models.DateField()),
                ('recipes', models.ManyToManyField(to='shopping_list_app.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.FloatField(max_length=6)),
                ('unit', models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pc', 'piece'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('pinch', 'pinch')], default='g')),
                ('category', models.CharField(choices=[('bakery and bread', ' Bakery and Bread'), ('meat and seafood', 'Meat and Seafood'), ('pasta and rice', 'Pasta and Rice'), ('oils and sauces', 'Oils and Sauces'), ('dairy and eggs', 'Dairy and eggs'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('spices', 'Spices'), ('other', 'Other')], default='Other')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shopping_list_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='IndependentIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.FloatField(max_length=6)),
                ('unit', models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pc', 'piece'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('pinch', 'pinch')], default='pc')),
                ('category', models.CharField(choices=[('bakery and bread', ' Bakery and Bread'), ('meat and seafood', 'Meat and Seafood'), ('pasta and rice', 'Pasta and Rice'), ('oils and sauces', 'Oils and Sauces'), ('dairy and eggs', 'Dairy and eggs'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('spices', 'Spices'), ('other', 'Other')], default='Other')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
