# Generated by Django 4.2.3 on 2023-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='independent_ingredients',
            field=models.ManyToManyField(blank=True, to='shopping_list_app.independentingredient'),
        ),
    ]
