# Generated by Django 4.2.3 on 2023-08-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0002_category_ingredient_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentIngredient',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopping_list_app.ingredient')),
            ],
            bases=('shopping_list_app.ingredient',),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shopping_list_app.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(default='Shopping list', max_length=128),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ManyToManyField(to='shopping_list_app.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('bakery and bread', ' Bakery and Bread'), ('meat and seafood', 'Meat and Seafood'), ('pasta and rice', 'Pasta and Rice'), ('oils and sauces', 'Oils and Sauces'), ('dairy and eggs', 'Dairy and eggs'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('spices', 'Spices'), ('other', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pc', 'piece'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('pinch', 'pinch')], default='g'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
