# Generated by Django 4.2.3 on 2023-08-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0002_shoppinglist_independent_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independentingredient',
            name='category',
            field=models.CharField(choices=[('bakery and bread', ' bakery and bread'), ('meat and seafood', 'meat and seafood'), ('pasta and rice', 'pasta and rice'), ('oils and sauces', 'oils and sauces'), ('dairy and eggs', 'dairy and eggs'), ('fruits', 'fruits'), ('vegetables', 'vegetables'), ('spices', 'spices'), ('other', 'other')], default='other'),
        ),
        migrations.AlterField(
            model_name='independentingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pc', 'piece'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('pinch', 'pinch'), ('btl', 'bottle')], default='pc'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('bakery and bread', ' bakery and bread'), ('meat and seafood', 'meat and seafood'), ('pasta and rice', 'pasta and rice'), ('oils and sauces', 'oils and sauces'), ('dairy and eggs', 'dairy and eggs'), ('fruits', 'fruits'), ('vegetables', 'vegetables'), ('spices', 'spices'), ('other', 'other')], default='other'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('ml', 'milliliter'), ('pc', 'piece'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('pinch', 'pinch'), ('btl', 'bottle')], default='g'),
        ),
    ]
